const TOURS = [
  {
    title: "Озеро Иссык-Куль", titleEn: "Lake Issyk-Kul",
    destination: "Иссык-Кульская область", destinationEn: "Issyk-Kul region",
    description: "Классический тур на самое большое озеро Кыргызстана с купанием и пляжным отдыхом.",
    descriptionEn: "A classic trip to the largest lake in Kyrgyzstan, with swimming and beach time.",
    about: "Трёхдневная поездка на южное побережье Иссык-Куля: пляжи, горячие источники и виды на хребет Тескей Ала-Тоо.",
    aboutEn: "A three-day trip to the southern shore of Issyk-Kul: beaches, hot springs and views of the Teskey Ala-Too range.",
    duration: "3 дня / 2 ночи", difficultyKey: "easy", iconKey: "water", price: 9500, totalSeats: 20,
    highlights: ["Пляжный отдых", "Горячие источники", "Фото-точки"],
    highlightsEn: ["Beach time", "Hot springs", "Photo spots"],
    itinerary: ["День 1: выезд из Бишкека, заселение, пляж", "День 2: горячие источники, прогулка по побережью", "День 3: свободное время, возвращение"],
    itineraryEn: ["Day 1: depart Bishkek, check-in, beach", "Day 2: hot springs, shoreline walk", "Day 3: free time, return"],
    included: ["Транспорт", "Проживание", "Завтраки"], includedEn: ["Transport", "Accommodation", "Breakfast"],
    groupSize: "до 16 человек", groupSizeEn: "up to 16 people",
    rating: 4.8, reviewsCount: 132,
  },
  {
    title: "Ущелье Ала-Арча", titleEn: "Ala-Archa Gorge",
    destination: "Чуйская область", destinationEn: "Chuy region",
    description: "Однодневный горный поход рядом с Бишкеком с видами на ледники.",
    descriptionEn: "A one-day mountain hike near Bishkek with glacier views.",
    about: "Национальный парк Ала-Арча — популярное место для однодневных походов в получасе от Бишкека, с маршрутами разной сложности.",
    aboutEn: "Ala-Archa National Park is a popular spot for day hikes just half an hour from Bishkek, with routes of varying difficulty.",
    duration: "1 день", difficultyKey: "medium", iconKey: "mountain", price: 2800, totalSeats: 14,
    highlights: ["Горный воздух", "Ледники", "Один день"], highlightsEn: ["Mountain air", "Glaciers", "One-day trip"],
    itinerary: ["Утро: выезд из Бишкека", "День: пеший маршрут по ущелью", "Вечер: возвращение в город"],
    itineraryEn: ["Morning: depart Bishkek", "Day: hike through the gorge", "Evening: return to the city"],
    included: ["Транспорт", "Гид", "Обед"], includedEn: ["Transport", "Guide", "Lunch"],
    groupSize: "до 12 человек", groupSizeEn: "up to 12 people",
    rating: 4.9, reviewsCount: 210,
  },
  {
    title: "Джайлоо и юрточный лагерь", titleEn: "Jailoo & Yurt Camp",
    destination: "Нарынская область", destinationEn: "Naryn region",
    description: "Ночёвка в юртах на высокогорном пастбище с местной кухней.",
    descriptionEn: "An overnight stay in yurts on a high-altitude pasture, with local cuisine.",
    about: "Погружение в кочевую культуру: ночёвка в настоящей юрте, катание на лошадях и традиционная кухня.",
    aboutEn: "An immersion into nomadic culture: a night in a real yurt, horseback riding and traditional food.",
    duration: "2 дня / 1 ночь", difficultyKey: "medium", iconKey: "tent", price: 7200, totalSeats: 12,
    highlights: ["Ночь в юрте", "Катание на лошадях", "Местная кухня"], highlightsEn: ["Night in a yurt", "Horseback riding", "Local cuisine"],
    itinerary: ["День 1: выезд, катание на лошадях, ужин у костра", "День 2: рассвет в горах, возвращение"],
    itineraryEn: ["Day 1: depart, horseback riding, campfire dinner", "Day 2: mountain sunrise, return"],
    included: ["Транспорт", "Проживание в юрте", "Питание"], includedEn: ["Transport", "Yurt stay", "Meals"],
    groupSize: "до 10 человек", groupSizeEn: "up to 10 people",
    rating: 4.7, reviewsCount: 88,
  },
  {
    title: "Перевал Тоссор", titleEn: "Tossor Pass",
    destination: "Иссык-Кульская область", destinationEn: "Issyk-Kul region",
    description: "Внедорожный маршрут через высокогорный перевал.",
    descriptionEn: "An off-road route over a high-altitude mountain pass.",
    about: "Насыщенный день на внедорожниках через один из самых живописных перевалов региона.",
    aboutEn: "A packed day in 4x4 vehicles through one of the most scenic passes in the region.",
    duration: "1 день", difficultyKey: "hard", iconKey: "rideshare", price: 4500, totalSeats: 6,
    highlights: ["Внедорожник", "Панорамные виды", "Активный день"], highlightsEn: ["4x4 vehicle", "Panoramic views", "Active day"],
    itinerary: ["Утро: выезд из Каракола", "День: подъём на перевал, фото-остановки", "Вечер: возвращение"],
    itineraryEn: ["Morning: depart Karakol", "Day: climb to the pass, photo stops", "Evening: return"],
    included: ["Внедорожник с водителем", "Обед", "Аптечка"], includedEn: ["4x4 with driver", "Lunch", "First-aid kit"],
    groupSize: "до 6 человек", groupSizeEn: "up to 6 people",
    rating: 4.6, reviewsCount: 54,
  },
  {
    title: "Зимний Каракол", titleEn: "Winter Karakol",
    destination: "Иссык-Кульская область", destinationEn: "Issyk-Kul region",
    description: "Горнолыжный уикенд на курорте Каракол.",
    descriptionEn: "A ski weekend at the Karakol resort.",
    about: "Два дня катания на горнолыжном курорте с видом на Терскей Ала-Тоо, для любого уровня подготовки.",
    aboutEn: "Two days of skiing at a resort with views of the Terskey Ala-Too range, suitable for any skill level.",
    duration: "2 дня / 1 ночь", difficultyKey: "medium", iconKey: "snow", price: 11000, totalSeats: 16,
    highlights: ["Горные лыжи", "Прокат снаряжения", "Отель у склона"], highlightsEn: ["Skiing", "Gear rental", "Hotel at the slope"],
    itinerary: ["День 1: заезд, катание", "День 2: катание, отъезд"], itineraryEn: ["Day 1: arrival, skiing", "Day 2: skiing, departure"],
    included: ["Проживание", "Ски-пасс на 1 день", "Трансфер"], includedEn: ["Accommodation", "1-day ski pass", "Transfer"],
    groupSize: "до 14 человек", groupSizeEn: "up to 14 people",
    rating: 4.8, reviewsCount: 97,
  },
  {
    title: "Долина Сары-Челек", titleEn: "Sary-Chelek Valley",
    destination: "Джалал-Абадская область", destinationEn: "Jalal-Abad region",
    description: "Поход к заповедному озеру среди ореховых лесов.",
    descriptionEn: "A hike to a protected lake set among walnut forests.",
    about: "Заповедник Сары-Челек — объект ЮНЕСКО с уникальной экосистемой и живописным горным озером.",
    aboutEn: "Sary-Chelek Reserve is a UNESCO site with a unique ecosystem and a scenic mountain lake.",
    duration: "3 дня / 2 ночи", difficultyKey: "hard", iconKey: "plant", price: 13500, totalSeats: 10,
    highlights: ["Заповедник ЮНЕСКО", "Ореховые леса", "Треккинг"], highlightsEn: ["UNESCO reserve", "Walnut forests", "Trekking"],
    itinerary: ["День 1: выезд, заселение", "День 2: треккинг к озеру", "День 3: возвращение"],
    itineraryEn: ["Day 1: depart, check-in", "Day 2: trek to the lake", "Day 3: return"],
    included: ["Транспорт", "Проживание", "Гид-натуралист"], includedEn: ["Transport", "Accommodation", "Naturalist guide"],
    groupSize: "до 10 человек", groupSizeEn: "up to 10 people",
    rating: 4.9, reviewsCount: 41,
  },
];

const GUIDES = [
  {
    name: "Нурлан Асанов", role: "Старший гид", roleEn: "Senior Guide",
    experience: "10+ лет опыта", experienceEn: "10+ years of experience",
    languages: ["Русский", "Кыргызский", "Английский"], languagesEn: ["Russian", "Kyrgyz", "English"],
    regions: ["Иссык-Куль", "Тянь-Шань"], regionsEn: ["Issyk-Kul", "Tian Shan"],
    bio: "Ведёт горные маршруты уже больше десяти лет, знает регион как свои пять пальцев.",
    bioEn: "Has been leading mountain routes for over ten years and knows the region inside out.",
  },
  {
    name: "Айгуль Жумабекова", role: "Гид-натуралист", roleEn: "Naturalist Guide",
    experience: "6+ лет опыта", experienceEn: "6+ years of experience",
    languages: ["Русский", "Английский"], languagesEn: ["Russian", "English"],
    regions: ["Сары-Челек", "Нарын"], regionsEn: ["Sary-Chelek", "Naryn"],
    bio: "Специализируется на заповедных территориях и экологических маршрутах.",
    bioEn: "Specializes in protected areas and ecological routes.",
  },
  {
    name: "Бакыт Эсенов", role: "Инструктор по треккингу", roleEn: "Trekking Instructor",
    experience: "8+ лет опыта", experienceEn: "8+ years of experience",
    languages: ["Кыргызский", "Русский"], languagesEn: ["Kyrgyz", "Russian"],
    regions: ["Ала-Арча", "Каракол"], regionsEn: ["Ala-Archa", "Karakol"],
    bio: "Сертифицированный инструктор, водит группы любого уровня подготовки.",
    bioEn: "A certified instructor who leads groups of any fitness level.",
  },
];

module.exports = { TOURS, GUIDES };
